name: Print only ci yaml

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'deploy-configs/**'
      - 'README.md'

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Console message
        run: |
          echo "Just simple message"
          echo "Done testing"